Vagrant.configure("2") do |config|
  # Client Machine
  config.vm.define "client" do |client|
    client.vm.box = "generic/alpine316"
    client.vm.network "private_network", ip: "192.168.56.4"
    client.vm.synced_folder "{{ base_dir }}/server", "/vagrant/server"
    client.vm.synced_folder "{{ result_dir }}", "/vagrant/results"

    client.vm.provision "shell", inline: <<-SHELL
      apk update
      apk add curl
      apk add tcpdump
      echo "export http_proxy=http://192.168.56.5:3128" >> /etc/profile
      source /etc/profile
    SHELL
  end

  # Proxy Machine
  config.vm.define "proxy" do |proxy|
    proxy.vm.box = "generic/alpine316"
    proxy.vm.network "private_network", ip: "192.168.56.5"
    proxy.vm.synced_folder "{{ base_dir }}/server", "/vagrant/server"
    proxy.vm.synced_folder "{{ result_dir }}", "/vagrant/results"

    proxy.vm.provision "shell", inline: <<-SHELL
      apk update
      apk add tcpdump
      # install 3proxy
      apk add make git gcc libc-dev linux-headers
      cd /home/vagrant
      git clone https://github.com/z3apa3a/3proxy
	  cd 3proxy
	  make -f Makefile.Linux
	  make -f Makefile.Linux install
	  # exchange chroot /usr/local/3proxy proxy proxy by chroot /usr/local/3proxy vagrant vagrant in "/etc/3proxy/3proxy.cfg"
	  sed -i 's|chroot /usr/local/3proxy proxy proxy|chroot /usr/local/3proxy vagrant vagrant|g' /etc/3proxy/3proxy.cfg
	  # change owner of 3proxy to avoid permission issues
	  sudo chown -R vagrant:vagrant /usr/local/3proxy
	  # add a user
	  chmod +x /usr/local/3proxy/conf/add3proxyuser.sh
	  /usr/local/3proxy/conf/add3proxyuser.sh vagrant vagrant
	  # exchange "auth strong" by "auth none" in "/etc/3proxy/3proxy.cfg"
	  sed -i 's/auth strong/auth none/g' /usr/local/3proxy/conf/3proxy.cfg
	  # start 3proxy
	  service 3proxy start

    SHELL
  end

  # Server Machine
  config.vm.define "server" do |server|
    server.vm.box = "generic/alpine316"
    server.vm.network "private_network", ip: "192.168.56.6"
    server.vm.synced_folder "{{ base_dir }}/server", "/vagrant/server"
    server.vm.synced_folder "{{ result_dir }}", "/vagrant/results"

    server.vm.provision "shell", inline: <<-SHELL
      apk update
      apk add tcpdump
      apk add python3
      sudo nohup python3 /vagrant/server/http1.py > /vagrant/results/server_out.log 2>&1 &
    SHELL
  end
end
