---
# do curl -fsSL https://eddie.website/repository/keys/eddie_maintainer_gpg.key | sudo tee /usr/share/keyrings/eddie.website-keyring.asc > /dev/null
- name: Import AirVPN key for validating signature
  shell:
    cmd: "curl -fsSL https://eddie.website/repository/keys/eddie_maintainer_gpg.key | sudo tee /usr/share/keyrings/eddie.website-keyring.asc > /dev/null"
  become: yes
- name: Import AirVPN Debian PPA Repository
  block:
    - name: Add AirVPN repository
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/eddie.website-keyring.asc] http://eddie.website/repository/apt stable main'
        state: present
        filename: 'eddie.website'

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
  become: yes
- name: Install AirVPN Eddie UI
  ansible.builtin.apt:
    name: eddie-ui
    state: present
  become: yes
- name: Install AirVPN Eddie UI
  ansible.builtin.apt:
    name: eddie-cli
    state: present
  become: yes
- name: Install OpenVPN
  ansible.builtin.apt:
    name: openvpn
    state: present
  become: yes
- name: Install Wireguard Client
  ansible.builtin.apt:
    name: wireguard
    state: present
  become: yes
- name: Download AirVPN Suite
  get_url:
    url: "https://eddie.website/repository/AirVPN-Suite/1.3.0/AirVPN-Suite-x86_64-1.3.0.tar.gz"
    dest: "/home/vagrant/AirVPN-Suite-x86_64-1.3.0.tar.gz"
- name: Extract AirVPN Suite
  unarchive:
    src: "/home/vagrant/AirVPN-Suite-x86_64-1.3.0.tar.gz"
    dest: "/home/vagrant/"
    remote_src: yes