---
- name: Download FRP
  ansible.builtin.get_url:
    url: "https://github.com/fatedier/frp/releases/download/v0.61.2/frp_0.61.2_linux_amd64.tar.gz"
    dest: "/root/frp.tar.gz"
- name: Extract FRP
  ansible.builtin.shell:
    cmd: "tar -xvf /root/frp.tar.gz -C /root"
- name: Rename FRP
  ansible.builtin.shell:
    cmd: "mv /root/frp_0.61.2_linux_amd64 /root/frp"
- name: "Change permissions"
  ansible.builtin.file:
    path: /root/frp/frps
    mode: '0755'
- name: Install certbot
  apt:
      name: certbot
      state: present
      update_cache: yes
- name: Check if cert dir already exists
  ansible.builtin.stat:
    path: /etc/letsencrypt/live/{{ hostvars['relay']['dns'] }}/
  register: cert_dir_status
- name: Create Cert
  command: certbot certonly --standalone --non-interactive --agree-tos --register-unsafely-without-email -d {{ hostvars['relay']['dns'] }}
  ignore_errors: yes
  when: cert_dir_status.stat.exists == false
- name: Copy crt to root
  ansible.builtin.copy:
    src: /etc/letsencrypt/live/{{ hostvars['relay']['dns'] }}/fullchain.pem
    dest: /root/server.crt
    remote_src: yes
- name: Copy key to root
  ansible.builtin.copy:
    src: /etc/letsencrypt/live/{{ hostvars['relay']['dns'] }}/privkey.pem
    dest: /root/server.key
    remote_src: yes