Vagrant.configure("2") do |config|
  config.vm.define "client" do |client|
    # Use the Ubuntu 20.04 box from Bento
    client.vm.box = "bento/ubuntu-24.04"

    # Synced folders
    client.vm.synced_folder "{{ result_dir }}", "/output"
    client.vm.synced_folder "{{ base_dir }}/client/{{ client }}", "/app"
    client.vm.synced_folder "{{ base_dir }}/cert", "/cert"

    # Provisioning script for Ubuntu
    client.vm.provision "shell", inline: <<-SHELL
      # Update package lists and install required packages
      sudo apt-get update
      sudo apt-get install -y curl python3 python3-pip tcpdump python3-dev build-essential linux-headers-generic libssl-dev python3-venv

      # create venv
      python3 -m venv /home/vagrant/venv
      source /home/vagrant/venv/bin/activate

      # Upgrade pip and install Python dependencies
      pip3 install --upgrade pip
      pip3 install -r /app/requirements.txt

      # Copy SSH keys from /cert to the vagrant user's .ssh directory
      cp /cert/id_rsa /home/vagrant/.ssh/id_rsa
      cp /cert/id_rsa.pub /home/vagrant/.ssh/id_rsa.pub

      # Ensure the SSH keys have the proper ownership and permissions
      sudo chown vagrant:vagrant /home/vagrant/.ssh/id_rsa /home/vagrant/.ssh/id_rsa.pub
      sudo chmod 600 /home/vagrant/.ssh/id_rsa
      sudo chmod 644 /home/vagrant/.ssh/id_rsa.pub
    SHELL
  end
end
