Vagrant.configure("2") do |config|
  config.vm.define "client" do |client|
    client.vm.box = "generic/alpine316"
    client.vm.synced_folder "{{ result_dir }}", "/output"
    client.vm.synced_folder "{{ base_dir }}/client/{{ client }}", "/app"
    client.vm.synced_folder "{{ base_dir }}/cert", "/cert"

    client.vm.provision "shell", inline: <<-SHELL
      sudo apk update
      sudo apk add curl
      sudo apk add python3
      sudo apk add tcpdump
      sudo apk add python3-dev gcc libc-dev build-base linux-headers bsd-compat-headers openssl-dev
      python3 -m ensurepip --upgrade
      pip3 install --upgrade pip
      pip3 install -r /app/requirements.txt
      cp /cert/id_rsa /home/vagrant/.ssh/id_rsa
      cp /cert/id_rsa.pub /home/vagrant/.ssh/id_rsa.pub
    SHELL
  end
end