---
- name: Install strongswan
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - strongswan
  become: yes
- name: Enable IPv4 forwarding
  sysctl:
      name: net.ipv4.ip_forward
      value: 1
      state: present
      sysctl_set: yes


