---
- name: Ensure necessary packages are installed
  ansible.builtin.apt:
    name:
      - wireguard
    state: present
  become: yes

- name: Load private key from file
  set_fact:
    private_client: "{{ lookup('file', 'setup/relay/wireguard/cert/private_client') }}"

- name: Load public server key from file
  set_fact:
    public_server: "{{ lookup('file', 'setup/relay/wireguard/cert/public_server') }}"

- name: Create Config with template
  become: yes
  template:
      src: setup/client/wireguard/wg0.conf.j2
      dest: /etc/wireguard/wg0.conf
      mode: '0600'
  vars:
    private_client: "{{ private_key }}"
    public_server: "{{ public_server }}"
    relay: "{{ hostvars['relay']['reserved_ip'] }}"



