---
# install shadowsocks
- name: Install Go
  ansible.builtin.command:
      cmd: snap install --classic go
  args:
      creates: /snap/bin/go
  become: yes
- name: Install shadowsocks
  ansible.builtin.command:
      cmd: go install github.com/shadowsocks/go-shadowsocks2@latest
  become: yes
- name: Deploy shadowsocks client systemd service file
  template:
    src: setup/client/shadowsocks/shadowsocksclient.service.j2
    dest: /etc/systemd/system/shadowsocksclient.service
    owner: vagrant
    group: vagrant
    mode: '0644'
  vars:
    relay: "{{ hostvars['relay']['reserved_ip'] }}"
    password: "fakepassword123"
  become: yes
- name: Enable service
  systemd:
    name: shadowsocksclient.service
    enabled: yes
    daemon_reload: yes
  become: yes