- name: "Detect type of target"
  set_fact:
    target_type: >-
      {% if target in vagrant_machines.keys() %}vagrant{% elif target in do_machines.keys() %}do{% else %}None{% endif %}
    machine: >-
      {{ (vagrant_machines | dict2items + do_machines | dict2items) 
      | selectattr('key', 'equalto', target) 
      | map(attribute='value') 
      | first }}

- name: "Check if target exists"
  fail:
    msg: "Target '{{ target }}' does not exist"
  when: target_type is none

- name: "Check if target is a host"
  fail:
    msg: "Target '{{ target }}' is not a host (most likely not started)"
  when: hostvars[target] is not defined

- name: "Get Host for machine"
  set_fact:
    host: "{{ hostvars[machine.name] }}"

- name: "Stop Vagrant machine"
  include_tasks: "vagrant.yml"
  when: target_type == 'vagrant'

- name: "Stop DigitalOcean droplet"
  include_tasks: "do.yml"
  when: target_type == 'do'