---
# Setup based on: https://www.digitalocean.com/community/tutorials/how-to-set-up-squid-proxy-on-ubuntu-20-04
- name: Install Squid with apt
  apt:
    name: squid
    state: present
- name: copy Squid configuration file
  copy:
      src: setup/relay/squid/squid.conf
      dest: /etc/squid/squid.conf
- name: Restart Squid service
  service:
    name: squid
    state: restarted
    enabled: yes


