---
- name: "Get Anchor IPv4"
  command: "curl -s http://169.254.169.254/metadata/v1/interfaces/public/0/anchor_ipv4/gateway"
  register: curl_result
- set_fact:
    anchor_ip: "{{ curl_result.stdout }}"
- name: "Disable cloud-init’s automatic network configuration"
  command: "echo 'network: {config: disabled}' | sudo tee /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg"
- name: "Set outbound traffic to originate from the reserved IP persistently"
  replace:
    path: /etc/netplan/50-cloud-init.yaml
    regexp: '(via:\s*)"[0-9\.]+"'
    replace: '\g<1>"{{ anchor_ip }}"'
- name: "Apply Changes"
  command: "netplan apply"