---
- name: "Detect type of target"
  set_fact:
    target_type: >-
      {% if target in vagrant_machines.keys() %}vagrant{% elif target in do_machines.keys() %}do{% else %}None{% endif %}
    machine: >-
      {{ (vagrant_machines | dict2items + do_machines | dict2items) 
      | selectattr('key', 'equalto', target) 
      | map(attribute='value') 
      | first }}
  delegate_to: localhost

- name: "print target type"
  debug:
      msg: "Target type is '{{ target_type }}'"

- fail:
    msg: "Target machine '{{ target }}' not found!"
  when: machine is none

- name: "Install net-tools"
  apt:
    name: net-tools
    state: present
  become: yes

- name: "Setup Do Machines"
  include_tasks: "do.yml"
  when: target_type == 'do'

- name: "Run provided setup tasks"
  include_tasks: "{{ setup }}"
  when: setup is defined