Vagrant.configure("2") do |config|
  config.vm.define "client" do |client|
    client.vm.box = "generic/alpine316"
    client.vm.synced_folder "X:/Masterarbeit/Repo/pcaps", "/vagrant/results"
    client.vm.synced_folder "X:/Masterarbeit/Repo/client", "/app"

    client.vm.provision "shell", inline: <<-SHELL
      apk update
      apk add curl
      apk add tcpdump
    SHELL
  end
end