Vagrant.configure("2") do |config|
  config.vm.define "client" do |client|
    client.vm.box = "generic/alpine316"
    client.vm.synced_folder "/home/miq/Documents/masterarbeit/proxydetection/test", "/output"
    client.vm.synced_folder "/home/miq/Documents/masterarbeit/proxydetection/client", "/app"
    client.vm.synced_folder "/home/miq/Documents/masterarbeit/proxydetection/cert", "/cert"

    client.vm.provision "shell", inline: <<-SHELL
      apk update
      apk add curl
      apk add python3
      apk add tcpdump
      python3 -m ensurepip --upgrade
      pip3 install --upgrade pip
      pip3 install /app/requirements.txt
      cp /cert/id_rsa /home/vagrant/.ssh/id_rsa
      cp /cert/id_rsa.pub /home/vagrant/.ssh/id_rsa.pub
    SHELL
  end
end