Vagrant.configure("2") do |config|
  config.vm.define "client" do |client|
    client.vm.box = "generic/alpine316"
    client.vm.synced_folder "/home/miq/Documents/masterarbeit/proxydetection/pcaps", "/vagrant/results"
    client.vm.synced_folder "/home/miq/Documents/masterarbeit/proxydetection/client", "/app"

    client.vm.provision "shell", inline: <<-SHELL
      apk update
      apk add curl
      apk add tcpdump
    SHELL
  end
end