- name: "Detect type of target"
  set_fact:
    target_type: >-
      {% if target in vagrant_machines.keys() %}vagrant{% elif target in do_machines.keys() %}do{% else %}None{% endif %}
    machine: >-
      {{ (vagrant_machines | dict2items + do_machines | dict2items) 
      | selectattr('key', 'equalto', target) 
      | map(attribute='value') 
      | first }}

- name: "Start Vagrant machine"
  include_tasks: vagrant.yml
  when: target_type == 'vagrant'

- name: "Start DigitalOcean droplet"
  include_tasks: do.yml
  when: target_type == 'do'

